/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Offer = IDL.Record({
  'contact' : IDL.Text,
  'date' : Time,
  'name' : IDL.Text,
  'price' : IDL.Nat,
});
export const Review = IDL.Record({
  'date' : Time,
  'name' : IDL.Text,
  'comment' : IDL.Text,
  'rating' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getAggregateRating' : IDL.Func([], [IDL.Float64], ['query']),
  'getAllOffers' : IDL.Func([], [IDL.Vec(Offer)], ['query']),
  'getAllReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'submitOffer' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  'submitReview' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Offer = IDL.Record({
    'contact' : IDL.Text,
    'date' : Time,
    'name' : IDL.Text,
    'price' : IDL.Nat,
  });
  const Review = IDL.Record({
    'date' : Time,
    'name' : IDL.Text,
    'comment' : IDL.Text,
    'rating' : IDL.Nat,
  });
  
  return IDL.Service({
    'getAggregateRating' : IDL.Func([], [IDL.Float64], ['query']),
    'getAllOffers' : IDL.Func([], [IDL.Vec(Offer)], ['query']),
    'getAllReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'submitOffer' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
    'submitReview' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };